/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Bureaucrat.h                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: aperis-p <aperis-p@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/05/28 18:44:14 by aperis-p          #+#    #+#             */
/*   Updated: 2024/06/02 20:45:09 by aperis-p         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef BUREAUCRAT_H
#define BUREAUCRAT_H

#include <string>
#include <iostream>
#include <fstream>
#include <cstdlib>
// #include "Classes/Form/Form.hpp"
// #include "Classes/Bureaucrat/Bureaucrat.hpp"

#define BLUE_GREEN	"\033[32;44m"
#define MAG_YE		"\033[33;45m"
#define RED     	"\033[1;31m"
#define GREEN   	"\033[1;32m"
#define YELLOW 		"\033[1;33m"
#define BLUE    	"\033[1;34m"
#define MAGENTA    	"\033[1;35m"
#define CYAN    	"\033[1;36m"
#define WHITE    	"\033[1;37m"
#define DFT   		"\033[0m"
#define TREE \
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKodKWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'.;d0MMWWWMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OXWNd..,xNOcoXWWNOo:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXc.'cOXOxOKk,:OWMXl...dWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OXMMMWWXxxXWW0,..'kWWWWX0XXNWd..;xNNo'oNNNWWMMMMMWN0kOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'.xWMMWWO'.;kNWKo,.dNXXNWKo,oXOokXWW0,.:Kx;oKWMMMXx;..cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,..oXXXNWK:..,OWNOodKN0OKKc..lNKll0WWNo,xXc..,kWWWd.':xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMK:.,OO;,;ckOo''OW0,.lNXkxKO'.cKXc.'kOlOXXWNd...:KNN0xkO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMWMM0c;lxX0d0WNOdoco0NOx0Wk'.:K0dd0XkkXMXc.l0c.'xWMWXd'.,kKOo:,..'oXMMMWMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMWWOd0NMWWWNx'..:0NXkc:kWMW0olcldxo:kWklxKXd:dNWKOKOc..lNMMWWKockd'..',:xXWMMXO0WMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMWo..:OKkxk0Od:;dOc.'lxdox0d,..,:lkNWdcxd;..;KWWO;:kd:xXkloKWkxX0kkOOc'oXWMNo.,OWMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0;..,dc...;oOX0xxkd;...oNXkxdokx:xXl,:'...:XWNl.dNWN0:..oNOl0MWWWWx...xWM0,..lNMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMWOoxKNKo,.dKl....'x0xKO'..;xNWx',cxKNx;l;';...'x0XN00NWNNx,;xNNloNXkod0d...dWWXc..dWMWWWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMNl..'c0WX0XWNOo:'.,ddOO:lk0XWWx....,xKl..lOl.ckl'dKXk:d00K0ddKk;xk,.'dXK:.;0MWWKoxKOockWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMWWd....,kWWNxckNNKOOOlxWXxc,oNMK:.....xx.'kWXKNXc.cOXO'.okOO'.cc;kkldxxdxOO0KNMMWNO:..'kWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMNkodOO:....:XWk'..dNWWWWocKd..;kklld;....:d',0WN0dOKdo0WNOcdkxo'.'.;0Xx:...cKNd'c0WXk;..;kNMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMWWNk,..:xl...:KWo...;KWWMMk,od:oo;..'kKl...co.;OOo..oXdxKxl::OKodl':';kc...:xXN0:..cOOkdoOXWWNWMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMWMMMWXxc,oXOc;xWWd...cXWkoOKc,ONd....lXWN0ccOl.co,...oolo;...lXWol0Kx':kdl::oKWKOo'.;oOWN0dlc;lKMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMWN0xolcclok0KK0kxk0XKc.cKM0,..od'cO;..;oockWWWW0;.lx:'.lccc...;lkNMx;kWd.cKk;..lXWOkXxcco0k:....;OWMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMNk:'......:odo:ck0kdoodkNWWk....::.;ldOO:..cXWWWk'.oXKOkc;kkox0Xo.,xk;lXl.cx,'cxNWNdxWWxcO0c;;:oOXWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMWO;',,,:ldkl'...o0kdol:;;o0WK:...'dc.:KWo..,c:lKWx..dWMNo'dNX0kxkkl..c;;d,.oK0KklOWOcONd;xWKdxXWMWWMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMNXXKXNWWNl...;xXkc::lx0k;'ckkc...x0:.;xd:d0c..:0d..oWWx.cOo,...,xX0dxl''..xWMK;.;Oll0l,xN0:.;0WWWWMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMWMMMWWWWKl;lkXWMMWWWNXKK0d,.,odooKW0:..:ONNd...ol..o0d,'o;....:dc:kWWd...,OWNO,.co,:;'dXWx..:0Odo0WMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMWNNWWWW0KWKo;,'',::;'..;lxOKk:...ck0o.'xl..;:..cc...;x0c..;0Wd...ckcl0kxx,..;Ox;dx:co:..c0WMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMWWMK:.lOko:,'..';oo,.....''.....;c,ckc......dx;ckNWXc..'OX:..'o;'dX0o,.'oKNl..xX0o:;cdxKWMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMWWNNNWXl..xWWWXOdocc:;........................'kNKk0NMWk'.o0l...lklcl:...:llckl.,xXKd;'..cKWMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMXd:;;:cxOc:0N0dc;,,,;;;,;c:::;,'...............'kKc.;0MMWOxx;....''....,lo:''oX0loOXOc:ldONWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMWNOdc;,',d0kdlcc:;,:k0dc,dNN0dl:cxOxlc,........ .xo..,0MWXkc............;oc,;ldoddool:::clx0NMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMWXOdoooxkkxdkKkc...:d;...oKl....oXMMMWXOd:.......;l'.oNKd,.......,:cllllccclloccxxc,......'lKWMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMWXo,...',cdokWMO,...ck:...,xl...;kNMMMMMMMWNO:......:okKx,.....':d0XWMMMMMMMMMMMKc..,cxkxxkOKNMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMN0kkkxoOXd.'kWx.'ckN0;..'xXo.:xXMMMMMWWMMWWWK:......:kc.....,dKWMMMMMMMMMMWWMMMMWKkxkKWMMMWMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMWXd,.d0;..cXXOKWMMWx,:OWMXKNMMMMMMMMMMMMMMM0;............lKWWMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMNo...xXc..oWMMMMMMMWXNWMMMMMMMMMMMMMMMMMMMMWx...........dNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMWWXc..oXWKldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.........cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMWWWOlkNWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,........xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d,......'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO:......'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0c......'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0c......'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0c......'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKk:.......kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0o,.......xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;'.......xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.........xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.........xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,.........;dk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Oxdddoooolc:'..............,cxKWMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0dl;'.................''...cdolc;...'lkNWMWMWXKOxxxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWOc...,coo:...,ldd:..'oOOKd...dXWWWXkc,...,lool:,'...,cccccx0NMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWWNKo'.;:c0WWk,.,xXWWWx..;0WWW0,...,cdkKNKOxc....,:ldOOkdlo0N0kl;;d0WMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Okxdl,..lKOkNMK;.;0WWWW0:..'kWWWWx..'...:oxkKNNk,.'kNWMWWWWNklkNWNd;lddxKWWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0OOOOOx:.,xNWK0WMk..xMMMXxlxo..dWWMMNk:cdc'.ckkxKWW0;.;KMMMWMMMMXkkXWNddNXOkOO0XNWWMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMWWWWWX0kxkkxxdl:,;oKWWWNNNO:.,0WXOkkXWx..xWMMMMMKcoX0c.;0X0XMWk'.oNMMMMMMMMWXKNWNxkNMMWXKKXXNWWMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMWWX0kkkxdd:,;coodkKNMMNK0Okxc..dNK0XWWNO;.:XMMMMMMM0oOMXc.lNNWMWd..,OWMMMMMMMMMWWWMW00XWMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMWX0OOKNWWKxxONWMWWWWMWXK000Oo;;xXWNWMWXo';;lNMMMMMMMNkOWK:.:KMMMK;:o,,kNMMWWMMMMMMMMMMNXNWWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMWNXKNWMMMMXxkWMMMMMMMMWNNWNkl:'cKMMWWMWO;,xXOl0MMMMMMMWK0xcc':KMMMO;dWKo:cdOXWMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMWNWMMMMMMMKkXMMMMMMMMMMWNkllkxoKMMMMMWO',0WW0xXMMMMMMMWXdlKK;cNWWWKcxWMMXo';oddkXWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKMMMMMMMMMWXdo0WNkOWWMMMMK:.lNWN0KWMMMMMMMWKd0W0;lWWWMWOd0WMMW0dx0OxdxXMWMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMWxdNMWWKKWMWWMMx:ll0WNNMMMMMMMMMMKONMO;:0WMWWWXO0XWMWN0OKNNOxKMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxKMMMWWWWMMMMMdlXkkWMMMMMMMMMMMMWXNW0lx00XNWMMWNNWWMMMMNXWMKONMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOXMMMMMMMMMMMMkoXXOXMMMMMMMMMMMMWWWWNdxWWNNWMMMMMMMMMMMMMMMWKNMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMXx0WNNMMMMMMMMMMMMMMMWWKkKWMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMXOXMMMMMMMMMMMMMMMMMMMMN0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\
#endif
