/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Bureaucrat.h                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: aperis-p <aperis-p@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/05/28 18:44:14 by aperis-p          #+#    #+#             */
/*   Updated: 2024/06/14 23:21:47 by aperis-p         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef BUREAUCRAT_H
#define BUREAUCRAT_H

#include <string>
#include <iostream>
#include <fstream>
#include <cstdlib>
#include <sstream>

#define BLUE_GREEN	"\033[32;44m"
#define MAG_YE		"\033[33;45m"
#define RED     	"\033[1;31m"
#define GREEN   	"\033[1;32m"
#define YELLOW 		"\033[1;33m"
#define BLUE    	"\033[1;34m"
#define MAGENTA    	"\033[1;35m"
#define CYAN    	"\033[1;36m"
#define WHITE    	"\033[1;37m"
#define DFT   		"\033[0m"
#define TREE \
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKodKWWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO°.:d0MMWWWMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OXWNd..,xNOcoXWWNOo:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXc.°cOXOxOKk,:OWMXl...dWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OXMMMWWXxxXWW0,..°kWWWWX0XXNWd..:xNNo°oNNNWWMMMMMWN0kOXWMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx°.xWMMWWO°.:kNWKo,.dNXXNWKo,oXOokXWW0,.:Kx:oKWMMMXx:..cKWMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,..oXXXNWK:..,OWNOodKN0OKKc..lNKll0WWNo,xXc..,kWWWd.°:xXWMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMWNWMMK:.,OO:,:ckOo°°OW0,.lNXkxKO°.cKXc.°kOlOXXWNd...:KNN0xkO0KXWMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMWMMMMMMWMM0c:lxX0d0WNOdoco0NOx0Wk°.:K0dd0XkkXMXc.l0c.°xWMWXd°.,kKOo:,..°oXMMMWMMMMMMMMMM\n\
MMMMMMMMMMMMMMMWWOd0NMWWWNx°..:0NXkc:kWMW0olcldxo:kWklxKXd:dNWKOKOc..lNMMWWKockd°..°,:xXWMMXO0WMMMMMMMM\n\
MMMMMMMMMMMMMMMMWo..:OKkxk0Od::dOc.°lxdox0d,..,:lkNWdcxd:..:KWWO::kd:xXkloKWkxX0kkOOc°oXWMNo.,OWMMMMMMM\n\
MMMMMMMMMMMMMMMMW0:..,dc...:oOX0xxkd:...oNXkxdokx:xXl,:°...:XWNl.dNWN0:..oNOl0MWWWWx...xWM0,..lNMMMMMMM\n\
MMMMMMMMMMMMWOoxKNKo,.dKl....°x0xKO°..:xNWx°,cxKNx:l:°:...°x0XN00NWNNx,:xNNloNXkod0d...dWWXc..dWMWWWMMM\n\
MMMMMMMMMMMMNl..°c0WX0XWNOo:°.,ddOO:lk0XWWx....,xKl..lOl.ckl°dKXk:d00K0ddKk:xk,.°dXK:.:0MWWKoxKOockWMMM\n\
MMMMMMMMMMMWWd....,kWWNxckNNKOOOlxWXxc,oNMK:.....xx.°kWXKNXc.cOXO°.okOO°.cc:kkldxxdxOO0KNMMWNO:..°kWMMM\n\
MMMMMMMMNkodOO:....:XWk°..dNWWWWocKd..:kklld:....:d°,0WN0dOKdo0WNOcdkxo°.°.:0Xx:...cKNd°c0WXk:..:kNMMMM\n\
MMMMMMWWNk,..:xl...:KWo...:KWWMMk,od:oo:..°kKl...co.:OOo..oXdxKxl::OKodl°:°:kc...:xXN0:..cOOkdoOXWWNWMM\n\
MMMMMWMMMWXxc,oXOc:xWWd...cXWkoOKc,ONd....lXWN0ccOl.co,...oolo:...lXWol0Kx°:kdl::oKWKOo°.:oOWN0dlc:lKMM\n\
MMWN0xolcclok0KK0kxk0XKc.cKM0,..od°cO:..:oockWWWW0:.lx:°.lccc...:lkNMx:kWd.cKk:..lXWOkXxcco0k:....:OWMM\n\
MNk:°......:odo:ck0kdoodkNWWk....::.:ldOO:..cXWWWk°.oXKOkc:kkox0Xo.,xk:lXl.cx,°cxNWNdxWWxcO0c:::oOXWMMM\n\
WO:°,,,:ldkl°...o0kdol:::o0WK:...°dc.:KWo..,c:lKWx..dWMNo°dNX0kxkkl..c::d,.oK0KklOWOcONd:xWKdxXWMWWMMMM\n\
MNXXKXNWWNl...:xXkc::lx0k:°ckkc...x0:.:xd:d0c..:0d..oWWx.cOo,...,xX0dxl°°..xWMK:.:Oll0l,xN0:.:0WWWWMMMM\n\
MWMMMWWWWKl:lkXWMMWWWNXKK0d,.,odooKW0:..:ONNd...ol..o0d,°o:....:dc:kWWd...,OWNO,.co,::°dXWx..:0Odo0WMMM\n\
MMMMMMMMMWNNWWWW0KWKo:,°°,:::°..:lxOKk:...ck0o.°xl..::..cc...:x0c..:0Wd...ckcl0kxx,..:Ox:dx:co:..c0WMMM\n\
MMMMMMMMMMMMWWMK:.lOko:,°..°:oo,.....°°.....:c,ckc......dx:ckNWXc..°OX:..°o:°dX0o,.°oKNl..xX0o::cdxKWMM\n\
MMMMMMMMMWWNNNWXl..xWWWXOdocc::........................°kNKk0NMWk°.o0l...lklcl:...:llckl.,xXKd:°..cKWMM\n\
MMMMMMMMXd::::cxOc:0N0dc:,,,:::,:c::::,°...............°kKc.:0MMWOxx:....°°....,lo:°°oX0loOXOc:ldONWMMM\n\
MMMMMMMWNOdc:,°,d0kdlcc::,:k0dc,dNN0dl:cxOxlc,........ .xo..,0MWXkc............:oc,:ldoddool:::clx0NMMM\n\
MMMMMMMWXOdoooxkkxdkKkc...:d:...oKl....oXMMMWXOd:.......:l°.oNKd,.......,:cllllccclloccxxc,......°lKWMM\n\
MMMMMWXo,...°,cdokWMO,...ck:...,xl...:kNMMMMMMMWNO:......:okKx,.....°:d0XWMMMMMMMMMMMKc..,cxkxxkOKNMMMM\n\
MMMMMMN0kkkxoOXd.°kWx.°ckN0:..°xXo.:xXMMMMMWWMMWWWK:......:kc.....,dKWMMMMMMMMMMWWMMMMWKkxkKWMMMWMMMMMM\n\
MMMMMMMMWXd,.d0:..cXXOKWMMWx,:OWMXKNMMMMMMMMMMMMMMM0:............lKWWMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMM\n\
MMMMMMMMNo...xXc..oWMMMMMMMWXNWMMMMMMMMMMMMMMMMMMMMWx...........dNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMWWXc..oXWKldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.........cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMWWWOlkNWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,........xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d,......°OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO:......°OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0c......°OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0c......°OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0c......°OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKk:.......kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0o,.......xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:°.......xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.........xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.........xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,.........:dk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Oxdddoooolc:°..............,cxKWMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0dl:°.................°°...cdolc:...°lkNWMWMWXKOxxxkOKNWMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWOc...,coo:...,ldd:..°oOOKd...dXWWWXkc,...,lool:,°...,cccccx0NMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMWMMWWWNKo°.::c0WWk,.,xXWWWx..:0WWW0,...,cdkKNKOxc....,:ldOOkdlo0N0kl::d0WMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMWX0Okxdl,..lKOkNMK:.:0WWWW0:..°kWWWWx..°...:oxkKNNk,.°kNWMWWWWNklkNWNd:lddxKWWMMM\n\
MMMMMMMMMMMMMMMMMMMWXK0OOOOOx:.,xNWK0WMk..xMMMXxlxo..dWWMMNk:cdc°.ckkxKWW0:.:KMMMWMMMMXkkXWNddNXOkOO0XN\n\
MMMMMMMMMMMMWWWWWX0kxkkxxdl:,:oKWWWNNNO:.,0WXOkkXWx..xWMMMMMKcoX0c.:0X0XMWk°.oNMMMMMMMMWXKNWNxkNMMWXKKX\n\
MMMMMMMMMMWWX0kkkxdd:,:coodkKNMMNK0Okxc..dNK0XWWNO:.:XMMMMMMM0oOMXc.lNNWMWd..,OWMMMMMMMMMWWWMW00XWMMMMM\n\
MMMMMMMMMWX0OOKNWWKxxONWMWWWWMWXK000Oo::xXWNWMWXo°::lNMMMMMMMNkOWK:.:KMMMK::o,,kNMMWWMMMMMMMMMMNXNWWMMM\n\
MMMMMMMWNXKNWMMMMXxkWMMMMMMMMWNNWNkl:°cKMMWWMWO:,xXOl0MMMMMMMWK0xcc°:KMMMO:dWKo:cdOXWMMMMMMMMMMMMMWWMMM\n\
MMMMMMMWNWMMMMMMMKkXMMMMMMMMMMWNkllkxoKMMMMMWO°,0WW0xXMMMMMMMWXdlKK:cNWWWKcxWMMXo°:oddkXWMMMWMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMWKKMMMMMMMMMWXdo0WNkOWWMMMMK:.lNWN0KWMMMMMMMWKd0W0:lWWWMWOd0WMMW0dx0OxdxXMWMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMNNMMMMMMMMMWxdNMWWKKWMWWMMx:ll0WNNMMMMMMMMMMKONMO::0WMWWWXO0XWMWN0OKNNOxKMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxKMMMWWWWMMMMMdlXkkWMMMMMMMMMMMMWXNW0lx00XNWMMWNNWWMMMMNXWMKONMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOXMMMMMMMMMMMMkoXXOXMMMMMMMMMMMMWWWWNdxWWNNWMMMMMMMMMMMMMMMWKNMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMXx0WNNMMMMMMMMMMMMMMMWWKkKWMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMXOXMMMMMMMMMMMMMMMMMMMMN0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"

#endif
